apiVersion: v1
kind: Secret
metadata:
  name: github-creds
  namespace: argo
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: $GITHUB_REPO
  username: $GITHUB_USER
  password: $GITHUB_TOKEN
