apiVersion: v1
kind: Secret
metadata:
  name: seldon-init-container-secret
  namespace: inference-test
type: Opaque
stringData:
  RCLONE_CONFIG_S3_TYPE: s3
  RCLONE_CONFIG_S3_PROVIDER: minio
  RCLONE_CONFIG_S3_ACCESS_KEY_ID: minio
  RCLONE_CONFIG_S3_SECRET_ACCESS_KEY: miniostorage
  RCLONE_CONFIG_S3_ENDPOINT: http://minio.flyte.svc.cluster.local:9000
  RCLONE_CONFIG_S3_ENV_AUTH: "false"
---
apiVersion: v1
kind: Secret
metadata:
  name: seldon-init-container-secret
  namespace: inference
type: Opaque
stringData:
  RCLONE_CONFIG_S3_TYPE: s3
  RCLONE_CONFIG_S3_PROVIDER: minio
  RCLONE_CONFIG_S3_ACCESS_KEY_ID: minio
  RCLONE_CONFIG_S3_SECRET_ACCESS_KEY: miniostorage
  RCLONE_CONFIG_S3_ENDPOINT: http://minio.flyte.svc.cluster.local:9000
  RCLONE_CONFIG_S3_ENV_AUTH: "false"
