apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  namespace: inference
  name: breast-cancer-clf
spec:
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - name: classifier
          image: k3d-registry.localhost:5000/classifier:d1eb231-6447
          imagePullPolicy: Always
    graph:
      name: classifier
      type: MODEL
      children: []
      parameters:
      - name: model_uri
        type: STRING
        value: "mlflow/0/5717b0ee9fbd44df8d73ba42a75ae00a/artifacts/model/model.pkl"
    name: default
    replicas: 1
