apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-server-deployment
  namespace: mlflow
  labels:
    app: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
        - name: mlflow-server
          image: k3d-registry.localhost:5000/mlflow:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: ARTIFACT_STORE
              value: s3://my-s3-bucket
            - name: MLFLOW_S3_ENDPOINT_URL
              value: http://minio.flyte:9000
            - name: AWS_ACCESS_KEY_ID
              value: minio
            - name: AWS_SECRET_ACCESS_KEY
              value: miniostorage
            - name: FILE_STORE
              value: postgresql://postgres:mlflow@postgres-service:5432/mlflow
