apiVersion: v1
kind: ServiceAccount
metadata:
  name: model-deployer-service-account
  namespace: flytesnacks-development
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: inference-test
  name: pod-controller
rules:
- apiGroups: ["machinelearning.seldon.io"]
  resources: ["seldondeployments", "seldondeployments/status"]
  verbs: ["get", "watch", "list", "create", "describe", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments", "deployments/status"]
  verbs: ["get", "watch", "list", "create", "describe", "delete"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "watch", "list", "create", "describe", "delete"]
- apiGroups: ["eventing.knative.dev"]
  resources: ["triggers", "triggers/status"]
  verbs: ["get", "watch", "list", "create", "describe", "delete"]
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: seldon-logs
  name: trigger-creator
rules:
- apiGroups: ["eventing.knative.dev"]
  resources: ["triggers", "triggers/status"]
  verbs: ["get", "watch", "list", "create", "describe", "delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-controller-rolebinding
  namespace: inference-test
subjects:
- kind: ServiceAccount
  name: model-deployer-service-account
  namespace: flytesnacks-development
roleRef:
  kind: Role
  name: pod-controller
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: trigger-creator-rolebinding
  namespace: seldon-logs
subjects:
- kind: ServiceAccount
  name: model-deployer-service-account
  namespace: flytesnacks-development
roleRef:
  kind: Role
  name: trigger-creator
  apiGroup: rbac.authorization.k8s.io
