{
 "title": "Real Time Statistical Performance",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "ACCURACY",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "((sum(seldon_metric_true_positive_total) by (seldon_deployment_name) + sum(seldon_metric_true_negative_total) by (seldon_deployment_name))  /  (sum(seldon_metric_true_positive_total) by (seldon_deployment_name) + sum(seldon_metric_false_positive_total) by (seldon_deployment_name) + sum(seldon_metric_false_negative_total) by (seldon_deployment_name) + sum(seldon_metric_true_negative_total) by (seldon_deployment_name))) ",
     "legendFormat": "{{class}} - {{seldon_app}}"
    }
   ]
  },
  {
   "title": "PRECISION",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(seldon_metric_true_positive_total) by (seldon_deployment_name)  /  (sum(seldon_metric_true_positive_total) by (seldon_deployment_name) + sum(seldon_metric_false_positive_total) by (seldon_deployment_name))) ",
     "legendFormat": "{{class}} - {{seldon_deployment_name}}"
    }
   ]
  },
  {
   "title": "Recall",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(seldon_metric_true_positive_total) by (seldon_deployment_name)  /  (sum(seldon_metric_true_positive_total) by (seldon_deployment_name) + sum(seldon_metric_false_negative_total) by (seldon_deployment_name))) ",
     "legendFormat": "{{class}} - {{seldon_app}}"
    }
   ]
  },
  {
   "title": "Real Time Model ACCURACY by Class",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "((sum(seldon_metric_true_positive_total) by (class, seldon_deployment_name) + sum(seldon_metric_true_negative_total) by (class, seldon_deployment_name))  /  (sum(seldon_metric_true_positive_total) by (class, seldon_deployment_name) + sum(seldon_metric_false_positive_total) by (class, seldon_deployment_name) + sum(seldon_metric_false_negative_total) by (class, seldon_deployment_name) + sum(seldon_metric_true_negative_total) by (class, seldon_deployment_name))) ",
     "legendFormat": "{{class}} - {{seldon_deployment_name}}"
    }
   ]
  },
  {
   "title": "Real Time Model PRECISION by Class",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "((sum(seldon_metric_true_positive_total) by (class, seldon_deployment_name))  /  (sum(seldon_metric_true_positive_total) by (class, seldon_deployment_name) + sum(seldon_metric_false_positive_total) by (class, seldon_deployment_name))) ",
     "legendFormat": "{{class}} - {{seldon_deployment_name}}"
    }
   ]
  },
  {
   "title": "Real Time Model RECALL by Class",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "((sum(seldon_metric_true_negative_total) by (class, seldon_deployment_name))  /  (sum(seldon_metric_true_positive_total) by (class, seldon_deployment_name) + sum(seldon_metric_false_negative_total) by (class, seldon_deployment_name))) ",
     "legendFormat": "{{class}} - {{seldon_deployment_name}}"
    }
   ]
  }
 ]
}